### ISSUE TITLE
Error Installing Add-on

### ISSUE THREAD

**Issue by aditiapratama** [BlenderAid/Asset-Flinger#2]
Hi Manu,

Somehow I've got this error when I want to install this addon from git

```
Exception in module register(): '/home/aditia/.config/blender/2.75/scripts/addons/add_mesh_asset_flinger/__init__.py'
Traceback (most recent call last):
  File "/home/aditia/blender-git/build_linux/bin/2.75/scripts/modules/addon_utils.py", line 343, in enable
    mod.register()
  File "/home/aditia/.config/blender/2.75/scripts/addons/add_mesh_asset_flinger/__init__.py", line 453, in register
    kmi.properties.use_selection = True
AttributeError: 'OperatorProperties' object has no attribute 'use_selection'

search for unknown operator 'EXPORT_SCENE_OT_obj', 'EXPORT_SCENE_OT_obj'
```

**Comment by aditiapratama** [comment]
Sorry, reverting blender to factory default solve the issue. It may come from another addon. I'll investigate further.

**Comment by aditiapratama** [comment]
Okay, it has some issue with amaranth add-on on my side.

**workaround**
_1. Disable amaranth addon_
_2. Enable asset flinger addon_
_3. Re-enable amaranth addon_

 Wil close it for now
